data: [

  current_world_population: 'f"Current World Population: {shared_world_data[0]}"',
  births_this_year: 'f"Births this year: {shared_world_data[1]}"',
  births_today: 'f"Births today: {shared_world_data[2]}"',
  deaths_this_year: 'f"Deaths this year: {shared_world_data[3]}"',
  deaths_today: 'f"Deaths today: {shared_world_data[4]}"',
  net_growth_this_year: 'f"Net growth this year: {shared_world_data[5]}"',
  net_growth_today: 'f"Net growth today: {shared_world_data[6]}"',
  public_healthcare_expenditure_today: 'f"Public healthcare expenditure today: $ {shared_world_data[7]}"',
  public_education_expenditure_today: 'f"Public education expenditure today: $ {shared_world_data[8]}"',
  public_military_expenditure_today: 'f"Military expenditure today: $ {shared_world_data[9]}"',
  cars_produced_this_year: 'f"Cars produced this year: {shared_world_data[10]}"',
  bicycles_produced_this_year: 'f"Bicycles produced this year: {shared_world_data[11]}"',
  computers_produced_this_year: 'f"Computers produced this year: {shared_world_data[12]}"',
  new_books_published_this_year: 'f"New books published this year: {shared_world_data[13]}"',
  newspapers_circulated_today: 'f"Newspapers circulated today: {shared_world_data[14]}"',
  tv_sets_sold_worldwide_today: 'f"TV sets sold worldwide today: {shared_world_data[15]}"',
  cellular_phones_sold_today: 'f"Cellular phones sold today: {shared_world_data[16]}"',
  money_spent_on_videogames_today: 'f"Money spent on videogames today: $ {shared_world_data[17]}"',
  internet_users_in_the_world_today: 'f"Internet users in the world today: {shared_world_data[18]}"',
  emails_sent_today: 'f"Emails sent today: {shared_world_data[19]}"',
  blog_posts_written_today: 'f"Blog posts written today: {shared_world_data[20]}"',
  tweets_sent_today: 'f"Tweets sent today: {shared_world_data[21]}"',
  google_searches_today: 'f"Google searches today: {shared_world_data[22]}"',
  forests_lost_this_year: 'f"Forest loss this year: {shared_world_data[23]}"',
  land_lost_to_soil_erosion_this_year: 'f"Land lost to soil erosion this year: {shared_world_data[24]}"',
  co2_emissions_this_year: 'f"CO2 emissions this year: {shared_world_data[25]}"',
  desertification_this_year: 'f"Desertification this year: {shared_world_data[26]}"',
  toxic_chemicals_released_in_the_environment_this_year: 'f"Toxic chemicals released in the environment this year: {shared_world_data[27]}"',
  undernourished_people_in_the_world: 'f"Undernourished people in the world: {shared_world_data[28]}"',
  overweight_people_in_the_world: 'f"Overweight people in the world: {shared_world_data[29]}"',
  obese_people_in_the_world: 'f"Obese people in the world: {shared_world_data[30]}"',
  people_who_died_of_hunger_today: 'f"People who died of hunger today: {shared_world_data[31]}"',
  money_spent_on_obesity_related_diseases_in_the_usa_today: 'f"Money spent on obesity related diseases in the USA today: $ {shared_world_data[32]}"',
  money_spent_on_weight_loss_programs_in_the_usa_today: 'f"Money spent on weight loss programs in the USA today: $ {shared_world_data[33]}"',
  water_used_this_year: 'f"Water used this year: {shared_world_data[34]}"',
  deaths_caused_by_water_related_diseases_this_year: 'f"Deaths caused by water related diseases this year: {shared_world_data[35]}"',
  people_with_no_access_to_a_safe_drinking_water_source: 'f"People with no access to a safe drinking water source: {shared_world_data[36]}"',
  energy_used_today: 'f"Energy used today: {shared_world_data[37]}"',
  from_non_renewable_sources: 'f"From non-renewable sources: {shared_world_data[38]}"',
  from_renewable_sources: 'f"From renewable sources: {shared_world_data[39]}"',
  solar_energy_striking_earth_today: 'f"Solar energy striking earth today: {shared_world_data[40]}"',
  oil_pumped_today: 'f"Oil pumped today: {shared_world_data[41]}"',
  oil_left: 'f"Oil left: {shared_world_data[42]}"',
  days_to_the_end_of_oil: 'f"Days to the end of oil: {shared_world_data[43]} (~{shared_world_data[44]} years)"',
  natural_gas_left: 'f"Natural gas left: {shared_world_data[45]}"',
  days_to_the_end_of_natural_gas: 'f"Days to the end of natural gas: {shared_world_data[46]}"',
  coal_left: 'f"Coal left: {shared_world_data[47]}"',
  days_to_the_end_of_coal: 'f"Days to the end of coal: {shared_world_data[48]}"',
  communicable_diseases_this_year: 'f"Communicable diseases this year: {shared_world_data[49]}"',
  seasonal_flu_deaths_this_year: 'f"Seasonal flu deaths this year: {shared_world_data[50]}"',
  deaths_of_children_under_5_this_year: 'f"Deaths of children under 5 this year: {shared_world_data[51]}"',
  abortions_this_year: 'f"Abortions this year: {shared_world_data[52]}"',
  deaths_of_mothers_during_birth_this_year: 'f"Deaths of mothers during birth this year: {shared_world_data[53]}"',
  hiv_aids_infected_people_this_year: 'f"HIV/AIDS infected people this year: {shared_world_data[54]}"',
  deaths_caused_by_hiv_aids_this_year: 'f"Deaths caused by HIV/AIDS this year: {shared_world_data[55]}"',
  deaths_caused_by_cancer_this_year: 'f"Deaths caused by cancer this year: {shared_world_data[56]}"',
  deaths_caused_by_malaria_this_year: 'f"Deaths caused by malaria this year: {shared_world_data[57]}"',
  cigarettes_smoked_today: 'f"Cigarettes smoked today: {shared_world_data[58]}"',
  deaths_caused_by_smoking_this_year: 'f"Deaths caused by smoking this year: {shared_world_data[59]}"',
  deaths_caused_by_alcohol_this_year: 'f"Deaths caused by alcohol this year: {shared_world_data[60]}"',
  suicides_this_year: 'f"Suicides this year: {shared_world_data[61]}"',
  money_spent_on_illegal_drugs_this_year: 'f"Money spent on illegal drugs this year: $ {shared_world_data[62]}"',
  road_traffic_accident_fatalities_this_year: 'f"Road traffic accident fatalities this year: {shared_world_data[63]}"',

]